//
// ../proxy.cpp
// Generated by the Pocomatic POCO DPP (Dynamic Proxy Generator), version 1.0
// from setup.xml
// Sat Feb 25 13:46:16 MSK 2012
//

#include <poco.h>
POCO_ENTRY(1330163176064)  // preserved

// ---------------------------------------
//  headers from -h/H options or setup.xml
// ---------------------------------------
#include "BeanExample.h"
	

// ---------------------------------------
//  Proxies of constructors and factories 
// ---------------------------------------
//
// new BeanExample()
//
static void* _poco_proxy_0(void* _poco_this, void* _poco_params[])
{
    BeanExample* _poco_var_retv;

    _poco_var_retv = new BeanExample();

    return (void*)_poco_var_retv;
}

static pocomatic_register_proxy _poco_proxy_var_0(
    0,
    "BeanExample*",
    "",
    "new BeanExample()",
    _poco_proxy_0,
    __FILE__,
    "_poco_proxy_0");

// -------------------------------------
//   Proxies of ioc methods on POCOs  
// -------------------------------------
//
// BeanExample::test()
//
static void* _poco_proxy_1(void* _poco_this, void* _poco_params[])
{
    BeanExample* _poco_var_this = (BeanExample*)_poco_this;

    _poco_var_this->test();

    return (void*)0UL;
}

static pocomatic_register_proxy _poco_proxy_var_1(
    1,
    "",
    "BeanExample*",
    "test()",
    _poco_proxy_1,
    __FILE__,
    "_poco_proxy_1");

// -------------------------------------
//   Proxies of dup and destroy methods 
// -------------------------------------
//
// delete(BeanExample*)
//
static void* _poco_proxy_2(void* _poco_this, void* _poco_params[])
{
    int _poco_i = 0;
    BeanExample* _poco_var_0 = (BeanExample*)(_poco_params[_poco_i++]);

    delete(
                _poco_var_0);

    return (void*)0UL;
}

static pocomatic_register_proxy _poco_proxy_var_2(
    2,
    "",
    "",
    "delete(BeanExample*)",
    _poco_proxy_2,
    __FILE__,
    "_poco_proxy_2");

// ------------------------------------
//   Proxies of POCO typecast methods  
// ------------------------------------
